# 20211207 media server
# docker-compose file for a media server ready with proper paths for instant move of files from downloader into proper media folders
# any places between "<>" must be changed (including the <>) to proper personal details
# I'll try to keep it documented but simple :)

version: "3"

services:

 plex:
  image: linuxserver/plex
  container_name: plex
  restart: unless-stopped
  network_mode: host
  environment:
   - PUID=<USER ID HERE> # find your current linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using '$ id' command in the terminal
   - VERSION=public
  volumes:
   - ${DOCKERDATA}/plex:/config
   - ${TVDIR}:/data/tvshows
   - ${MOVIESDIR}:/data/movies
   - ${MUSICDIR}:/data/music
   - ${MUSICDIR}-video:/data/music-video
   - ${PICSDIR}:/data/pics
  devices:
   - /dev/dri:/dev/dri # For H/W transcoding

 lidarr:
  image: linuxserver/lidarr
  container_name: lidarr
  restart: unless-stopped
  environment:
   - PUID=<USER ID HERE> # find your linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using same '$ id' command in the terminal
   - TZ=${TZ}
  volumes:
   - ${DOCKERDATA}/lidarr:/config
   - ${MUSICDIR}:/music
   - ${DOWNLOADDIR}:/downloads
  ports:
   - 8686:8686

 radarr:
  image: linuxserver/radarr
  container_name: radarr
  restart: unless-stopped
  environment:
   - PUID=<USER ID HERE> # find your linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using same '$ id' command in the terminal
   - TZ=${TZ}
  volumes:
   - ${DOCKERDATA}/radarr:/config
   - ${MOVIESDIR}:/movies
   - ${DOWNLOADDIR}:/downloads
  ports:
   - 7878:7878

 sonarr:
  image: linuxserver/sonarr
  container_name: sonarr
  restart: unless-stopped
  environment:
   - PUID=<USER ID HERE> # find your linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using same '$ id' command in the terminal
   - TZ=${TZ}
  volumes:
   - ${DOCKERDATA}/sonarr:/config
   - ${TVDIR}:/tv
   - ${DOWNLOADDIR}:/downloads
  ports:
   - 8989:8989

 transmission:
  image: linuxserver/transmission
  container_name: transmission
  restart: unless-stopped
  environment:
   - PUID=<USER ID HERE> # find your linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using same '$ id' command in the terminal
   - USER=${TRANSMISSION_USER}
   - PASS=${TRANSMISSION_PASS}
   - TZ=${TZ}
   - TRANSMISSION_WEB_HOME=${TRANSMISSION_WEB}
   - UMASK=${UMASK}
  volumes:
   - ${DOCKERDATA}/transmission:/config
   - ${WATCHDIR}:/watch
   - ${DOWNLOADDIR}:/downloads
  ports:
   - 9091:9091
   - 51413:51413
   - 51413:51413/udp

 bazarr:
  image: linuxserver/bazarr
  container_name: bazarr
  restart: unless-stopped
  environment:
   - PUID=<USER ID HERE> # find your linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using same '$ id' command in the terminal
   - TZ=${TZ}
  volumes:
   - ${DOCKERDATA}/bazarr:/config
   - ${MOVIESDIR}:/movies
   - ${TVDIR}:/tv
  ports:
   - 6767:6767

 jackett:
  image: linuxserver/jackett
  container_name: jackett
  restart: unless-stopped
  environment:
   - PUID=<USER ID HERE> # find your linux user id using command '$ id' in the terminal
   - PGID=<GROUP ID HERE> # find your current linux group id using same '$ id' command in the terminal
   - TZ=${TZ}
  volumes:
   - ${DOCKERDATA}/jackett:/config
   - ${WATCHDIR}:/downloads
  ports:
   - 9117:9117

   